name: "Forum Api"
on: ["push", "pull_request", "release"]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  QUAYIO_PASSWORD: ${{ secrets.QUAYIO_PASSWORD }}
  QUAYIO_USERNAME: ${{ secrets.QUAYIO_USERNAME }}
jobs:
  
  unit_test:
    runs-on: ubuntu-latest
    env:
      MONGODB: '4.1.1'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: test
        run: |
          cp config/test.json.example config/test.json
          cp config/default.json.example config/default.json
          wget -q http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
          tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
          mkdir ./mongodb-linux-x86_64-${MONGODB}/data
          ./mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ./mongodb-linux-x86_64-${MONGODB}/data --logpath ./mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
          ./mongodb-linux-x86_64-${MONGODB}/bin/mongo forumDb --eval 'db.createUser({user:"forumUser", pwd:"forumPass", roles:["dbAdmin", "readWrite"]});'
          npm test

  quay_io:
    runs-on: ubuntu-latest
    needs: ["unit_test"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: push to quay
        run: |
          export BRANCH=${GITHUB_REF##*/}
          chmod ugo+x ./docker_quayio_push
          ./docker_quayio_push ocwa_forum_api

  deploy:
    runs-on: ubuntu-latest
    needs: ["quay_io"]
    if: success() && ( (github.event_name == 'release' && github.event.action == 'created') || (github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/develop') )
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: push to dockerhub
        run: |
          export BRANCH=${GITHUB_REF##*/}
          chmod ugo+x ./docker_push
          ./docker_push ocwa_forum_api